version: '3'

tasks:
  debug:
    cmds:
      - go run main.go -debug

  test:
    cmds:
      - go test ./...

  build-all:
      cmds:
        - mkdir -p bin
        - GOOS=linux GOARCH=amd64 go build -o bin/ktcloud_linux_amd64
        - GOOS=linux GOARCH=386 go build -o bin/ktcloud_linux_386
        - GOOS=darwin GOARCH=amd64 go build -o bin/ktcloud_darwin_amd64
        - GOOS=windows GOARCH=amd64 go build -o bin/ktcloud_windows_amd64.exe
        - GOOS=windows GOARCH=386 go build -o bin/ktcloud_windows_386.exe